Add old version detection

diff --git a/.github/workflows/integrate-pr.yaml b/.github/workflows/integrate-pr.yaml
--- a/.github/workflows/integrate-pr.yaml
+++ b/.github/workflows/integrate-pr.yaml
@@ -67,6 +67,42 @@ jobs:
           SDK=$(grep '^ARG OPERATOR_SDK_VERSION=' env/build/Dockerfile | sed 's/ARG OPERATOR_SDK_VERSION=//')
           echo "version=$SDK" >> $GITHUB_OUTPUT
 
+      - name: Compute OLD_VERSION
+        id: old-operator-version
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          CURRENT_VERSION="${{ steps.operator-version.outputs.version }}"
+
+          # Ensures tags are available
+          git fetch --tags --force
+
+          # Gets latest semver tag LOWER than CURRENT_VERSION:
+          # here we must old fight against the gaps. This is not perfect since it does not handle
+          # all SemVer cases, but only the ones that we need
+          OLD_VERSION=$(
+            {
+              git tag \
+                | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' \
+                | sed 's/^v//'
+              echo "$CURRENT_VERSION"
+            } |
+            sort -V |
+            awk -v cur="$CURRENT_VERSION" '
+              $0 == cur { print prev; exit }
+              { prev = $0 }
+            '
+          )
+
+          if [[ -z "$OLD_VERSION" ]]; then
+            echo "ERROR: No previous semantic version tag found lower than $CURRENT_VERSION"
+            exit 1
+          fi
+
+          echo "OLD_VERSION=$OLD_VERSION"
+          echo "old_version=$OLD_VERSION" >> "$GITHUB_OUTPUT"
+
       # -------------------------------
       # Install Operator SDK binary
       # -------------------------------
@@ -110,7 +146,10 @@ jobs:
       - name: Patch manifests
         run: |
           CSV="operator/bundle/manifests/spark-operator.clusterserviceversion.yaml"
-          ./scripts/patch-csv.sh --file $CSV --min-kube-version ${{ steps.minkube-version.outputs.minkube }}
+          ./scripts/patch-csv.sh \
+            --file $CSV \
+            --min-kube-version "${{ steps.minkube-version.outputs.minkube }}" \
+            --old-operator-version "${{ steps.old-operator-version.outputs.old_version }}"
 
       # -------------------------------
       # Detect changes
